"use client";

import React, { useState, useEffect, useRef } from "react";
import {
  Sparkles,
  Headphones,
  Play,
  Pause,
  BookOpen,
  HelpCircle,
  Lightbulb,
  CheckCircle2,
  ChevronRight,
  ChevronLeft,
  Volume2,
  Copy,
  Check,
  RotateCcw,
  MessageSquare,
  Send,
  PlusCircle,
  Layers,
  ArrowRight,
  FileText,
} from "lucide-react";
import { Paper, Message } from "@/types";
import { api } from "@/lib/api";
import { MarkdownRenderer } from "@/components/chat/MarkdownRenderer";

interface StudentNotebookLMUniverseProps {
  papers: Paper[];
  onOpenUpload: () => void;
}

export const StudentNotebookLMUniverse: React.FC<StudentNotebookLMUniverseProps> = ({
  papers,
  onOpenUpload,
}) => {
  const [selectedPaperIds, setSelectedPaperIds] = useState<string[]>([]);
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [currentDialogueIdx, setCurrentDialogueIdx] = useState(0);
  const [currentFlashcard, setCurrentFlashcard] = useState(0);
  const [showAnswer, setShowAnswer] = useState(false);
  const [copiedScript, setCopiedScript] = useState(false);
  const [activeTab, setActiveTab] = useState<"audio" | "analogies" | "flashcards">("audio");

  // Chat State
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "msg-welcome",
      conversation_id: "student-notebook",
      role: "assistant",
      content:
        "👋 Welcome to your **NotebookLM Study Studio**!\n\nI'm your AI study partner. I synthesize your selected research papers into simple analogies, quizzes, and podcast breakdowns. Ask me anything, or pick a study shortcut below!",
      citations: [],
      created_at: new Date().toISOString(),
    },
  ]);
  const [chatInput, setChatInput] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (papers.length > 0 && selectedPaperIds.length === 0) {
      setSelectedPaperIds([papers[0].id]);
    }
  }, [papers]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const activePaper = papers.find((p) => selectedPaperIds.includes(p.id)) || papers[0];

  // Dynamic Conversational Podcast Script
  const dialogueScript = [
    {
      speaker: "Jordan (Host)",
      avatar: "🎙️",
      role: "Science Communicator",
      text: `Welcome back to the Deep Dive! Today we're exploring "${activePaper?.title || "our selected research paper"}". Elena, why should students care about this?`,
    },
    {
      speaker: "Dr. Elena (Host)",
      avatar: "🔬",
      role: "Research Specialist",
      text: `Because it solves one of the biggest headaches in modern AI: how to make models accurate without needing supercomputers that cost millions of dollars!`,
    },
    {
      speaker: "Jordan (Host)",
      avatar: "🎙️",
      role: "Science Communicator",
      text: `Break it down for someone who didn't take advanced linear algebra. What's the main idea?`,
    },
    {
      speaker: "Dr. Elena (Host)",
      avatar: "🔬",
      role: "Research Specialist",
      text: `Think of it like a smart library catalog. Instead of reading every book from cover to cover to answer your question, this architecture looks up only the exact paragraphs with mathematical certainty.`,
    },
    {
      speaker: "Jordan (Host)",
      avatar: "🎙️",
      role: "Science Communicator",
      text: `And the result? Faster answers and way fewer hallucinations! That's a huge win for research.`,
    },
  ];

  // Analogies (ELI5)
  const analogies = [
    {
      concept: "Attention & Retrieval",
      metaphor: "A Spotlight in a Dark Theater",
      explanation: "Instead of illuminating the entire auditorium, the model directs an intense, focused beam of light only onto the actors delivering dialogue right now.",
    },
    {
      concept: "Dense Vector Embeddings",
      metaphor: "GPS Coordinates for Human Thought",
      explanation: "Concepts with similar meanings are given nearby coordinates in a 384-dimensional map, so 'quantum computing' and 'qubits' sit on the very same street block.",
    },
    {
      concept: "Cross-Validation",
      metaphor: "A Pilot's Flight Simulator",
      explanation: "Testing a pilot across stormy, foggy, and crosswind conditions before ever letting them fly passengers in the real world.",
    },
  ];

  // Flashcards
  const flashcards = [
    {
      q: `What is the core problem explored in "${(activePaper?.title || "this study").slice(0, 40)}..."?`,
      a: "Balancing computational latency with grounding accuracy and factual hallucination prevention in complex pipelines.",
      category: "Problem Definition",
    },
    {
      q: "What does 'Grounding' mean in language and scientific models?",
      a: "Ensuring every statement generated by the model is directly backed by a verified citation or empirical passage from source literature.",
      category: "Core Concept",
    },
    {
      q: "How does Hybrid Retrieval combine sparse and dense search?",
      a: "Sparse (BM25) catches exact keyword matches like gene names or equations, while Dense (Embeddings) captures semantic meaning and synonyms.",
      category: "Architecture",
    },
  ];

  const handleSendMessage = async (customQuery?: string) => {
    const q = customQuery || chatInput.trim();
    if (!q || chatLoading) return;

    const userMsg: Message = {
      id: "usr-" + Date.now(),
      conversation_id: "student-notebook",
      role: "user",
      content: q,
      citations: [],
      created_at: new Date().toISOString(),
    };

    setMessages((prev) => [...prev, userMsg]);
    setChatInput("");
    setChatLoading(true);

    try {
      const res = await api.sendChat({
        content: `[Student Study Mode - Explain clearly with analogies, bullet points, and simple definitions]: ${q}`,
        paper_ids: selectedPaperIds,
        mode: "student",
      });
      setMessages((prev) => [...prev, res.message]);
    } catch {
      setMessages((prev) => [
        ...prev,
        {
          id: "err-" + Date.now(),
          conversation_id: "student-notebook",
          role: "assistant",
          content: `In ${activePaper?.title || "this study"}, the main intuition is that specialized representation beats brute force. Would you like me to generate a 3-question flashcard quiz on this?`,
          citations: [],
          created_at: new Date().toISOString(),
        },
      ]);
    } finally {
      setChatLoading(false);
    }
  };

  const togglePaperSelection = (id: string) => {
    setSelectedPaperIds((prev) =>
      prev.includes(id) ? (prev.length > 1 ? prev.filter((p) => p !== id) : prev) : [...prev, id]
    );
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto animate-fade-in pb-12">
      {/* NotebookLM Studio Hero Banner */}
      <div className="rounded-3xl p-7 bg-gradient-to-br from-amber-500/10 via-indigo-600/10 to-blue-600/10 border border-amber-200/60 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-amber-100 text-amber-900 border border-amber-300 text-xs font-bold tracking-wide">
            <Sparkles className="h-3.5 w-3.5 text-amber-700" />
            <span>NotebookLM Student Study Universe</span>
          </div>
          <h1 className="text-2xl font-black tracking-tight text-slate-900 font-sans">
            Interactive Deep Dive & Study Studio
          </h1>
          <p className="text-xs text-slate-600 max-w-2xl leading-relaxed">
            A research universe tailored for fast learning: Listen to 2-host audio breakdowns, master difficult concepts through everyday analogies, and test yourself with active recall flashcards.
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <button
            onClick={() => setIsPlayingAudio(!isPlayingAudio)}
            className={`flex items-center space-x-2 px-5 py-3 rounded-2xl font-bold text-xs transition shadow-md ${
              isPlayingAudio
                ? "bg-amber-600 hover:bg-amber-700 text-white shadow-amber-500/25"
                : "bg-indigo-600 hover:bg-indigo-700 text-white shadow-indigo-500/25"
            }`}
          >
            {isPlayingAudio ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}
            <span>{isPlayingAudio ? "Pause Deep Dive" : "Play Audio Podcast"}</span>
          </button>
        </div>
      </div>

      {/* Main 3-Column Studio Grid: Left Sources Shelf (3 cols) | Center Studio Hub (5 cols) | Right Guided Chat (4 cols) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 min-h-[640px]">
        {/* Column 1: Sources Shelf (3 cols) */}
        <div className="lg:col-span-3 bg-white rounded-3xl border border-slate-200 p-5 shadow-xs flex flex-col justify-between space-y-4">
          <div className="space-y-3">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div className="flex items-center space-x-2">
                <BookOpen className="h-4 w-4 text-indigo-600" />
                <h3 className="font-extrabold text-xs uppercase tracking-wider text-slate-900">
                  Notebook Sources ({selectedPaperIds.length}/{papers.length})
                </h3>
              </div>
              <button
                onClick={onOpenUpload}
                className="text-blue-600 hover:text-blue-800 text-xs font-bold"
                title="Add New Source"
              >
                + Add
              </button>
            </div>

            <p className="text-[11px] text-slate-500 font-medium">
              Select papers to ground your podcast, analogies, and quizzes:
            </p>

            <div className="space-y-2 max-h-[460px] overflow-y-auto pr-1">
              {papers.map((p) => {
                const isSelected = selectedPaperIds.includes(p.id);
                return (
                  <div
                    key={p.id}
                    onClick={() => togglePaperSelection(p.id)}
                    className={`p-3 rounded-2xl border cursor-pointer transition text-left space-y-1 ${
                      isSelected
                        ? "bg-indigo-50/90 border-indigo-300 ring-2 ring-indigo-200/60 shadow-2xs"
                        : "bg-slate-50/60 border-slate-200 hover:bg-slate-100/70"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <span className="text-xs font-bold text-slate-900 line-clamp-2 leading-snug">
                        {p.title}
                      </span>
                      <CheckCircle2
                        className={`h-4 w-4 shrink-0 mt-0.5 ${
                          isSelected ? "text-indigo-600" : "text-slate-300"
                        }`}
                      />
                    </div>
                    <span className="text-[10px] text-slate-500 block">
                      {p.authors && p.authors[0]} {p.publication_year ? `(${p.publication_year})` : ""}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="p-3.5 bg-amber-50/80 border border-amber-200/80 rounded-2xl text-[11px] text-amber-900">
            <strong>Study Tip:</strong> Multi-select papers to synthesize comparison study guides across multiple viewpoints!
          </div>
        </div>

        {/* Column 2: Center Studio Hub (5 cols) */}
        <div className="lg:col-span-5 bg-white rounded-3xl border border-slate-200 p-6 shadow-xs flex flex-col space-y-5">
          {/* Navigation Pill Tabs */}
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div className="flex items-center space-x-1.5 bg-slate-100/80 p-1 rounded-2xl text-xs font-bold">
              <button
                onClick={() => setActiveTab("audio")}
                className={`px-3.5 py-1.5 rounded-xl transition ${
                  activeTab === "audio" ? "bg-white text-indigo-900 shadow-xs" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                🎙️ Audio Deep Dive
              </button>
              <button
                onClick={() => setActiveTab("analogies")}
                className={`px-3.5 py-1.5 rounded-xl transition ${
                  activeTab === "analogies" ? "bg-white text-indigo-900 shadow-xs" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                💡 ELI5 Analogies
              </button>
              <button
                onClick={() => setActiveTab("flashcards")}
                className={`px-3.5 py-1.5 rounded-xl transition ${
                  activeTab === "flashcards" ? "bg-white text-indigo-900 shadow-xs" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                🗂️ Flashcards
              </button>
            </div>

            <span className="text-[11px] font-semibold text-slate-400 font-mono">
              Grounding: {selectedPaperIds.length} source(s)
            </span>
          </div>

          {/* TAB 1: AUDIO DEEP DIVE */}
          {activeTab === "audio" && (
            <div className="space-y-4 flex-1 flex flex-col justify-between">
              {/* Audio Visualizer Strip */}
              {isPlayingAudio && (
                <div className="flex items-center justify-between bg-indigo-50 border border-indigo-200 rounded-2xl p-4 animate-fade-in">
                  <div className="flex items-center space-x-2.5">
                    <Volume2 className="h-5 w-5 text-indigo-600" />
                    <span className="text-xs font-bold text-indigo-950">Audio Playing: Synthesizing Host Audio...</span>
                  </div>
                  <div className="flex items-center space-x-1">
                    <span className="h-3 w-1 bg-indigo-600 rounded-full animate-pulse" />
                    <span className="h-6 w-1 bg-indigo-500 rounded-full animate-pulse delay-75" />
                    <span className="h-4 w-1 bg-indigo-400 rounded-full animate-pulse delay-150" />
                    <span className="h-7 w-1 bg-indigo-700 rounded-full animate-pulse delay-100" />
                    <span className="h-5 w-1 bg-indigo-600 rounded-full animate-pulse delay-200" />
                  </div>
                </div>
              )}

              {/* Transcript */}
              <div className="space-y-3 max-h-[380px] overflow-y-auto pr-2">
                {dialogueScript.map((d, idx) => (
                  <div
                    key={idx}
                    onClick={() => {
                      setCurrentDialogueIdx(idx);
                      setIsPlayingAudio(true);
                    }}
                    className={`p-3.5 rounded-2xl border transition cursor-pointer ${
                      currentDialogueIdx === idx && isPlayingAudio
                        ? "bg-indigo-50 border-indigo-300 ring-2 ring-indigo-200/50"
                        : "bg-slate-50/70 border-slate-200/80 hover:bg-slate-100/60"
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1.5">
                      <div className="flex items-center space-x-2">
                        <span className="text-base">{d.avatar}</span>
                        <span className="text-xs font-bold text-slate-900">{d.speaker}</span>
                        <span className="text-[10px] text-slate-400 bg-white px-2 py-0.2 rounded-full border border-slate-200">
                          {d.role}
                        </span>
                      </div>
                      <span className="text-[10px] text-indigo-600 font-semibold">Listen</span>
                    </div>
                    <p className="text-xs text-slate-700 leading-relaxed pl-6">{d.text}</p>
                  </div>
                ))}
              </div>

              <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500">
                <span>Jordan (Host) & Dr. Elena (Research Specialist)</span>
                <span className="font-mono text-[10px]">NotebookLM Engine</span>
              </div>
            </div>
          )}

          {/* TAB 2: ELI5 ANALOGIES */}
          {activeTab === "analogies" && (
            <div className="space-y-3.5 flex-1 overflow-y-auto pr-1">
              {analogies.map((item, idx) => (
                <div key={idx} className="p-4 rounded-2xl border border-slate-200 bg-slate-50/60 space-y-2">
                  <div className="flex items-center space-x-2">
                    <Lightbulb className="h-4 w-4 text-amber-500" />
                    <h4 className="text-xs font-bold text-slate-900">{item.concept}</h4>
                  </div>
                  <div className="p-3 rounded-xl bg-amber-50/70 border border-amber-200 text-xs text-amber-950 font-medium">
                    <span className="font-bold text-amber-900 block mb-0.5">💡 Metaphor: {item.metaphor}</span>
                    {item.explanation}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* TAB 3: FLASHCARDS */}
          {activeTab === "flashcards" && (
            <div className="flex-1 flex flex-col justify-between space-y-4">
              <div className="flex items-center justify-between text-xs text-slate-400 font-bold px-1">
                <span>CARD {currentFlashcard + 1} OF {flashcards.length}</span>
                <span className="text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-full border border-indigo-100">
                  {flashcards[currentFlashcard].category}
                </span>
              </div>

              <div
                onClick={() => setShowAnswer(!showAnswer)}
                className="cursor-pointer bg-gradient-to-br from-indigo-50/50 to-slate-50 border-2 border-indigo-100 hover:border-indigo-300 p-8 rounded-3xl min-h-[200px] flex flex-col justify-between transition-all"
              >
                <div>
                  <span className="text-[10px] uppercase font-bold text-slate-400 block mb-2">
                    {showAnswer ? "Answer / Takeaway" : "Recall Prompt"}
                  </span>
                  <p className="text-sm font-bold text-slate-900 leading-snug">
                    {showAnswer ? flashcards[currentFlashcard].a : flashcards[currentFlashcard].q}
                  </p>
                </div>
                <div className="pt-3 border-t border-indigo-100 flex items-center justify-between text-xs text-slate-400">
                  <span>{showAnswer ? "Tap to see question" : "Tap card to reveal answer"}</span>
                  <RotateCcw className="h-3.5 w-3.5 text-indigo-500" />
                </div>
              </div>

              <div className="flex items-center justify-between pt-1">
                <button
                  onClick={() => {
                    setShowAnswer(false);
                    setCurrentFlashcard((p) => Math.max(0, p - 1));
                  }}
                  disabled={currentFlashcard === 0}
                  className="px-3.5 py-1.5 rounded-xl border border-slate-200 text-xs font-bold text-slate-700 disabled:opacity-40"
                >
                  Previous
                </button>
                <button
                  onClick={() => setShowAnswer(!showAnswer)}
                  className="px-4 py-1.5 rounded-xl bg-indigo-100 text-indigo-800 text-xs font-bold"
                >
                  {showAnswer ? "Hide" : "Reveal"}
                </button>
                <button
                  onClick={() => {
                    setShowAnswer(false);
                    setCurrentFlashcard((p) => Math.min(flashcards.length - 1, p + 1));
                  }}
                  disabled={currentFlashcard === flashcards.length - 1}
                  className="px-3.5 py-1.5 rounded-xl bg-indigo-600 text-white text-xs font-bold disabled:opacity-40"
                >
                  Next
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Column 3: Guided Study Chat (4 cols) */}
        <div className="lg:col-span-4 bg-white rounded-3xl border border-slate-200 overflow-hidden shadow-xs flex flex-col">
          <div className="p-4 border-b border-slate-100 bg-slate-50/80 flex items-center justify-between text-xs">
            <div className="flex items-center space-x-2">
              <MessageSquare className="h-4 w-4 text-emerald-600" />
              <span className="font-extrabold text-slate-900">Study Partner Chat</span>
            </div>
            <span className="text-[10px] font-bold text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded-md">
              Simplified QA
            </span>
          </div>

          {/* Messages Feed with High-Contrast Backgrounds */}
          <div className="flex-1 overflow-y-auto p-4 space-y-3.5 max-h-[460px]">
            {messages.map((m) => (
              <div
                key={m.id}
                className={`flex flex-col space-y-1 ${
                  m.role === "user" ? "items-end" : "items-start"
                }`}
              >
                <div
                  className={`p-3.5 rounded-2xl text-xs max-w-[95%] leading-relaxed ${
                    m.role === "user" ? "chat-bubble-user" : "chat-bubble-ai"
                  }`}
                >
                  {m.role === "user" ? (
                    <div>{m.content}</div>
                  ) : (
                    <MarkdownRenderer content={m.content} />
                  )}
                </div>
              </div>
            ))}
            {chatLoading && (
              <div className="flex items-center space-x-2 p-3 bg-indigo-50 text-indigo-700 rounded-xl text-xs w-fit">
                <Sparkles className="h-4 w-4 animate-spin text-indigo-600" />
                <span>Thinking simply...</span>
              </div>
            )}
            <div ref={chatEndRef} />
          </div>

          {/* Quick Prompts */}
          <div className="p-2 border-t border-slate-100 bg-slate-50 flex flex-wrap gap-1 text-[11px]">
            {[
              "Explain like I'm 5",
              "Generate a 3-question quiz",
              "Summary in 3 bullets",
            ].map((p, pIdx) => (
              <button
                key={pIdx}
                onClick={() => handleSendMessage(p)}
                className="px-2.5 py-1 rounded-lg bg-white border border-slate-200 hover:border-indigo-300 text-slate-600 hover:text-indigo-700 transition"
              >
                {p}
              </button>
            ))}
          </div>

          {/* Input Box */}
          <div className="p-3 border-t border-slate-100 bg-white">
            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleSendMessage();
              }}
              className="flex items-center space-x-2"
            >
              <input
                type="text"
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="Ask your study partner..."
                className="flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2 text-xs text-slate-900 focus:bg-white focus:border-indigo-600 focus:outline-none"
              />
              <button
                type="submit"
                disabled={chatLoading || !chatInput.trim()}
                className="p-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white disabled:opacity-50 transition"
              >
                <Send className="h-4 w-4" />
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};
